// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxtT-XupLd4F_vJHjzmhau0S1QuaQVFqM',
    appId: '1:627496204476:web:83850ec6824c0c8b4bf8b9',
    messagingSenderId: '627496204476',
    projectId: 'darbs-app',
    authDomain: 'darbs-app.firebaseapp.com',
    storageBucket: 'darbs-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHEBElgIS-yIAvhGlQPMe-wykHITH8RPE',
    appId: '1:627496204476:android:b9a24e9e0e7079e24bf8b9',
    messagingSenderId: '627496204476',
    projectId: 'darbs-app',
    storageBucket: 'darbs-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG_D2wC-1qew5aowQkVvqBEKgHhlx2i_8',
    appId: '1:627496204476:ios:ce530e713b4b31694bf8b9',
    messagingSenderId: '627496204476',
    projectId: 'darbs-app',
    storageBucket: 'darbs-app.firebasestorage.app',
    androidClientId: '627496204476-ppiv40p21jf5o082fv158u2io9r1o8i7.apps.googleusercontent.com',
    iosClientId: '627496204476-p8i0f7ru3j5tq3qfhm8im4on9gpph2fk.apps.googleusercontent.com',
    iosBundleId: 'com.example.darbFoodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG_D2wC-1qew5aowQkVvqBEKgHhlx2i_8',
    appId: '1:627496204476:ios:ce530e713b4b31694bf8b9',
    messagingSenderId: '627496204476',
    projectId: 'darbs-app',
    storageBucket: 'darbs-app.firebasestorage.app',
    androidClientId: '627496204476-ppiv40p21jf5o082fv158u2io9r1o8i7.apps.googleusercontent.com',
    iosClientId: '627496204476-p8i0f7ru3j5tq3qfhm8im4on9gpph2fk.apps.googleusercontent.com',
    iosBundleId: 'com.example.darbFoodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxtT-XupLd4F_vJHjzmhau0S1QuaQVFqM',
    appId: '1:627496204476:web:c7da5263442b92384bf8b9',
    messagingSenderId: '627496204476',
    projectId: 'darbs-app',
    authDomain: 'darbs-app.firebaseapp.com',
    storageBucket: 'darbs-app.firebasestorage.app',
  );

}